version: '3'

services:
  streamlit-app:
    build: .
    container_name: streamlit-app
    networks:
      - app-network

  nginx:
    build: ./reverse_proxy
    container_name: nginx
    ports:
      - "443:443"  # HTTPS port
      - "80:80"    # HTTP port (for redirect)
    depends_on:
      - streamlit-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 